sudo: false
language: node_js
node_js:
  - 8

dist: xenial
services:
  - xvfb

env:
  global:
    - CXX=g++-4.8
    - GH_REF: github.com/ima-worldhealth/ui-select.git
    - GH_PAGES_BRANCH: gh-pages
    - secure: "PkIhXXwrR5fHh7fH+2WizaY0MmK1l1Dr7PCqs112PkEimVPcntRJeA5pjTwGRwHm+RSkFVtfo38EY/GUwzhLSRTO7WZ+id+vIMGQLgiofqrOwi0nq93esG6qI8Jg5K0GUt8mzg5m9B2tgm2I91RAojEhIukKcbsDsq3hNAUy71Y="

addons:
  firefox: "31.0"

  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - npm install --quiet -g gulp

script: "gulp test"

after_success:
  - "gulp docs"

git:
  depth: 3
